apiVersion: v1
kind: Service
metadata:
  name: haquocbao.id.vn-service
  namespace: haquocbao-domain
spec:
  selector:
    app: haquocbao.id.vn
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
